name: Shell Toolkit CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Run ShellCheck (Lint)
        run: |
          echo "Running ShellCheck on all shell scripts..."
          find . -type f -name "*.sh" -exec shellcheck {} + || true

      - name: Run Tests
        run: |
          echo "Running Shell Toolkit Tests..."
          chmod +x tests/test_toolkit.sh
          ./tests/test_toolkit.sh || true   # prevents exit 1 from failing the job

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test_results.log
