name: Shell Toolkit CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Install dependencies
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      # 3. Lint all shell scripts
      - name: Lint Shell Scripts
        run: |
          echo "Running ShellCheck..."
          shellcheck $(find . -type f -name "*.sh")

      # 4. Make scripts executable
      - name: Make scripts executable
        run: chmod +x toolkit.sh utils/*.sh tests/*.sh

      # 5. Run automated tests with failure detection
      - name: Run Shell Toolkit Tests
        run: |
          echo "Running Shell Toolkit Tests..."
          ./tests/test_toolkit.sh
          STATUS=$?
          if [ $STATUS -ne 0 ]; then
            echo "::error ::Some scripts failed. See test_results.log for details."
            exit 1
          else
            echo "All scripts passed successfully!"
          fi

      # 6. Upload test logs
      - name: Upload Test Logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: shell-toolkit-test-logs
          path: test_results.log
